development:
  adapter: postgresql
  encoding: unicode
  database: daily_development
  pool: 5
  username: sblock
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: daily_test
  pool: 5
  username: sblock
  password: